# Generated by Django 3.2 on 2023-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_sms',
            field=models.CharField(default=1695813105.760765, max_length=100),
        ),
    ]
